services:
  pipeline:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      # paths
      - DB_PATH=/app/data/warehouse.duckdb
      - OUTPUT_DIR=/app/outputs
      - LOG_LEVEL=INFO
      - ENVIRONMENT=local
    volumes:
      - ./docs/sample-data:/app/docs/sample-data
      - ./scripts:/app/scripts
      - ./outputs:/app/outputs
    command: tail -f /dev/null
